"""initial migration

Revision ID: ff4c5cb2837d
Revises: 
Create Date: 2025-05-05 06:21:58.897373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4c5cb2837d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('file', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_schema'
    )
    op.create_index(op.f('ix_fastapi_schema_pdfs_id'), 'pdfs', ['id'], unique=False, schema='fastapi_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_schema_pdfs_id'), table_name='pdfs', schema='fastapi_schema')
    op.drop_table('pdfs', schema='fastapi_schema')
    # ### end Alembic commands ###
